name: Pull and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set Tag Name
        id: tag_name
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"
        shell: bash

      - 
        name: Project Name to Lowercase
        run: echo "PROJECT_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Pull Image
        run: docker pull --platform ${{ matrix.platform }} dehim/${{ env.PROJECT_NAME }}:${{ steps.tag_name.outputs.tag }}

      -
        name: Tag Image
        run: docker tag dehim/${{ env.PROJECT_NAME }}:${{ steps.tag_name.outputs.tag }} ${YOUR_DOCKERHUB_USERNAME}/${{ env.PROJECT_NAME }}:${{ steps.tag_name.outputs.tag }}-${{ matrix.platform }}

      -
        name: Push Image
        run: docker push ${YOUR_DOCKERHUB_USERNAME}/${{ env.PROJECT_NAME }}:${{ steps.tag_name.outputs.tag }}-${{ matrix.platform }}
